package com.aajeevika.buyer.utility

const val KEY_COUNTRY_ID = "country_id"
const val KEY_STATE_ID = "state_id"
const val KEY_MOBILE = "mobile"
const val KEY_CATEGORY_ID = "categoryId"
const val KEY_SUB_CATEGORY_ID = "subcategoryId"
const val KEY_PRODUCT_ID = "productId"
const val KEY_PAGE = "page"
const val KEY_OTP = "otp"
const val KEY_TYPE = "type"
const val KEY_PASSWORD = "password"
const val KEY_NAME = "name"
const val KEY_EMAIL = "email"
const val KEY_ROLE_ID = "role_id"
const val KEY_PROMOTIONAL_MAIL = "is_promotional_mail"
const val KEY_ADDRESS_LINE_ONE = "address_line_one"
const val KEY_ADDRESS_LINE_TWO = "address_line_two"
const val KEY_VILLAGE = "village"
const val KEY_PIN_CODE = "pincode"
const val KEY_COUNTRY = "country"
const val KEY_STATE = "state"
const val KEY_DISTRICT = "district"
const val KEY_ID = "id"
const val KEY_ARTISAN_ID = "artisanshgid"
const val KEY_KEYWORD = "keyword"
